# .github/workflows/ci.yml

name: CI/CD Forum App

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Unit & Integration Tests
        run: npm test

      # Untuk E2E, Anda perlu menjalankan server.
      # Saya akan mengasumsikan Anda akan menambahkan 'start-server-and-test'
      # atau menjalankan server di background seperti yang saya sarankan sebelumnya.
      # Jika tidak, Cypress akan gagal karena tidak menemukan aplikasi berjalan.

      - name: Run E2E Tests
        run: npm run e2e:ci
        env:
          CI: true
          # Tambahkan env vars yang dibutuhkan aplikasi saat E2E testing di sini
          # Contoh: REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL_TEST }}

  deploy:
    needs: build-and-test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js (for build)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies (for build)
        run: npm ci

      - name: Build React App
        run: npm run build
        env:
          CI: false
          # Tambahkan env vars yang dibutuhkan aplikasi saat build untuk production di sini
          # Contoh: REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL_PROD }}

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.NHywseAex4ODXOAvNb1H0vWf }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.prj_uHbKmWg5hLLnkwD9xElNc5RYxJct }}
          vercel-args: '--prod' # Aktifkan ini untuk deploy otomatis ke production alias
        # Tidak perlu blok 'env:' di sini jika tidak ada variabel khusus untuk Vercel Action itu sendiri.
        # Variabel lingkungan untuk aplikasi React (saat build di Vercel)
        # sebaiknya dikelola di Vercel Dashboard langsung atau di langkah 'Build React App' di atas.